Cadastro de Secreitarias

. Nome completo da secretaria
. MASP 
. CPF
. Email institucional
. Turno
. Senha 


Cadastro de Alunos

. Nome completo do aluno
. ID 
. CPF
. Data de nascimento
. Turma
. Turmo
. Genêro
. Raça
. Nacionalidade/Naturalidade
. Nome do responsável
. CPF do responsável
. Telefone do responsável
. Email do responsável
. Endereço completo


Cadastro de Turmas

. Nome da turma
. ID da turma
. Turno


Atrasos e Saídas Antecipadas

. ID do aluno
. ID da turma
. Nome do aluno
. Nome da turma
. Data do atraso/saída antecipada
. Hora do atraso/saída antecipada
. Tipo da ocorrência (atraso ou saída antecipada)
. Justificativa da ocorrência
. Observações adicionais (opcional)


Anexo de atestados médicos e outros documentos

. Tipo de documento (atestado médico, declaração, etc.)
. Imagem do documento 
. Descrição/Observações
