Cadastro de Secreitarias

. Nome completo da secretaria: Cleide Helena Da Silva
. MASP : 123456
. CPF: 111.222.333-44
. Email institucional:  cleidehelena@educacao.mg.gov.br
. Turno: Manhã
. Senha : 1183281


. Nome completo da secretaria: Maria Aparecida De Oliveira
. MASP : 654321
. CPF: 222.333.444-55
. Email institucional: mariaaparecida@educacao.mg.gov.br
. Turno: Tarde
. Senha : 222952


. Nome completo da secretaria: Joana Da Silva Souza
. MASP : 789012
. CPF: 333.444.555-66
. Email institucional: joanadasilva@educacao.mg.gov.br
. Turno: Noite
. Senha : 377533


. Nome completo da secretaria: Jaqueline Souza
. MASP : 345678
. CPF: 444.555.666-77
. Email institucional: jaquelinesouza@educacao.mg.gov.br
. Turno: Manhã
. Senha : 4535398




Cadastro de Alunos

. Nome completo do aluno: João Pedro de Oliveira
. ID : 108640
. CPF: 555.666.777-88
. Data de nascimento: 15/03/2008
. Turma: 3º Ano 1
. Turmo: Manhã
. Genêro: Masculino
. Raça: Branca
. Nacionalidade/Naturalidade: Brasileiro
. Nome do responsável: Maria Aparecida de Oliveira
. CPF do responsável: 222.333.444-55
. Telefone do responsável: (31) 99999-9999
. Email do responsável: mariaaparecida@gmail.com
. Endereço completo: Rua Exemplo, 823 - Bairro Exemplo - Santa Rita Do Sapucaí - MG 

Cadastro de Alunos

. Nome completo do aluno: Ana Beatriz Souza
. ID : 108641
. CPF: 666.777.888-99
. Data de nascimento: 22/07/2009
. Turma: 2º Ano 2
. Turmo: Manhã
. Genêro: Feminino
. Raça: Branca
. Nacionalidade/Naturalidade: Brasileira
. Nome do responsável: João da Silva Souza
. CPF do responsável: 333.444.555-66
. Telefone do responsável: (31) 99999-9999
. Email do responsável: joao11@gmail.com
. Endereço completo: Rua Exemplo, 1923 - Bairro Exemplo - Santa Rita Do Sapucaí - MG 



. Nome completo do aluno: Carlos Eduardo Lima
. ID : 108642
. CPF: 777.888.999-00
. Data de nascimento: 10/11/2011
. Turma: 1º Ano 1
. Turmo: Manhã
. Genêro: Masculino
. Raça: Parda
. Nacionalidade/Naturalidade: Brasileiro
. Nome do responsável: Fernanda Lima
. CPF do responsável: 444.555.666-77
. Telefone do responsável: (31) 99999-9999
. Email do responsável: fernandalima@gmail.com
. Endereço completo: Rua Exemplo, 1883 - Bairro Exemplo - Santa Rita Do Sapucaí - MG


. Nome completo do aluno: Gabriel Henrique Santos
. ID :  108643
. CPF: 688.999.000-11
. Data de nascimento: 05/05/2014 
. Turma: 7º Ano 2
. Turmo: Tarde
. Genêro: Masculino
. Raça: Parda
. Nacionalidade/Naturalidade: Brasileiro
. Nome do responsável: Luana Santos
. CPF do responsável: 055.666.777-88   
. Telefone do responsável: (31) 99999-9999
. Email do responsável: luanasantos123@gmail.com
. Endereço completo: Rua Exemplo, 123 - Bairro Exemplo - Santa Rita Do Sapucaí - MG 



. Nome completo do aluno:  Pamela Rodrigues
. ID : 108644
. CPF: 777.888.999-00
. Data de nascimento: 15/03/2008
. Turma: 3º Ano 1
. Genêro: Feminino
. Raça: Branca
. Nacionalidade/Naturalidade: Brasileira
. Nome do responsável: Helena Rodrigues
. CPF do responsável: 055.666.777-88   
. Telefone do responsável: (31) 99999-9999
. Email do responsável: helena.rodrigues@gmail.com
. Endereço completo: Rua Exemplo, 45 - Bairro Exemplo - Santa Rita Do Sapucaí - MG 




Cadastro de Turmas

. Nome da turma : 6º Ano 1
. ID da turma : 101564
. Turno : Tarde

. Nome da turma: 6º Ano 2
. ID da turma: 101565
. Turno: Tarde

. Nome da turma: 7º Ano 1
. ID da turma: 101566
. Turno: Tarde

. Nome da turma: 7º Ano 2
. ID da turma: 101567
. Turno: Tarde

. Nome da turma: 8º Ano 1
. ID da turma: 101568
. Turno: Manhã

. Nome da turma: 8º Ano 2
. ID da turma: 101569
. Turno: Manhã

. Nome da turma: 9º Ano 1
. ID da turma: 101570
. Turno: Manhã

. Nome da turma: 9º Ano 2
. ID da turma: 101571
. Turno: Manhã

. Nome da turma: 1º Ano 1
. ID da turma: 101572
. Turno: Manhã

. Nome da turma: 1º Ano 2
. ID da turma: 101573
. Turno: Manhã

. Nome da turma:  1º Ano Técnico em Energias Renovaveis
. ID da turma: 1015744
. Turno: Integral

. Nome da turma: 2º Ano 1
. ID da turma: 101574
. Turno: Manhã

. Nome da turma: 2º Ano 2
. ID da turma: 101575
. Turno: Manhã

. Nome da turma: 2º Ano Técnico em Energias Renovaveis
. ID da turma: 101575
. Turno: Integral

. Nome da turma: 3º Ano 1
. ID da turma: 101576
. Turno: Manhã

. Nome da turma: 3º Ano 2
. ID da turma: 101577
. Turno: Manhã

. Nome da turma: 3º Ano Técnico em Informática
. ID da turma: 101578
. Turno: Integral



Atrasos e Saídas Antecipadas

. ID do aluno : 108640
. ID da turma: 101576
. Nome do aluno: João Pedro de Oliveira
. Nome da turma: 3º Ano 1
. Data do atraso/saída antecipada: 4/10/2026
. Hora do atraso/saída antecipada: 8:10
. Tipo da ocorrência (atraso ou saída antecipada): Atraso
. Justificativa da ocorrência: Médico 
. Observações adicionais (opcional): 


Anexo de atestados médicos e outros documentos

. Tipo de documento (atestado médico, declaração): Atestado médico
. Imagem do documento : .png
. Descrição/Observações:  


. ID do aluno : 108641
. ID da turma: 101577
. Nome do aluno: Ana Beatriz Souza
. Nome da turma: 2º Ano 2
. Data do atraso/saída antecipada:  15/08/2026
. Hora do atraso/saída antecipada: 12:30
. Tipo da ocorrência (atraso ou saída antecipada): Saída antecipada
. Justificativa da ocorrência: Trabalho
. Observações adicionais (opcional):


Anexo de atestados médicos e outros documentos

. Tipo de documento (atestado médico, declaração): Declaração
. Imagem do documento :
. Descrição/Observações: 


. ID do aluno : 108642
. ID da turma: 101574
. Nome do aluno: Carlos Eduardo Lima
. Nome da turma: 1º Ano 1
. Data do atraso/saída antecipada: 29/09/2026
. Hora do atraso/saída antecipada: 8:40
. Tipo da ocorrência (atraso ou saída antecipada): Atraso
. Justificativa da ocorrência: Ficou preso no trânsito
. Observações adicionais (opcional):


Anexo de atestados médicos e outros documentos

. Tipo de documento (atestado médico, declaração)
. Imagem do documento :
. Descrição/Observações: Ficou preso no trânsito e não conseguiu chegar a tempo na escola, por isso se atrasou.



